# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f code/backend/requirements.txt ]; then pip install -r code/backend/requirements.txt; fi
        cd code/backend/
        curl -O https://download.oracle.com/otn_software/linux/instantclient/218000/instantclient-basiclite-linux.x64-21.8.0.0.0dbru.zip 
        unzip instantclient-basiclite-linux.x64-21.8.0.0.0dbru.zip 
        
        mv -f admin/* instantclient_21_8/network/admin/
        echo ${{ secrets.EWALLET }} > admin/ewallet.pem
              
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Add folders to Python Path
      run: |
          echo "PYTHONPATH=code/backend" >> $GITHUB_ENV
    - name: Test with pytest
      env:
        ORACLE_HOME: code/backend/instantclient_21_8
        DYLD_LIBRARY_PATH: $ORACLE_HOME
        LD_LIBRARY_PATH: $ORACLE_HOME
        PATH: $ORACLE_HOME:$PATH
        TNS_ADMIN: $ORACLE_HOME/network/admin
      run: |
        pytest tests/tests.py
    - name: Setup tmate session
      if: success() || failure()
      uses: mxschmitt/action-tmate@v3
